server:
  port: 8090
mybatis:
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.dayuan.entity

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie?useUnicode=true&characterEncoding=utf-8
    username: root
    password: "027459"

dubbo:
  application:
    name: provider
  registry:
    address: zookeeper://182.61.40.169:2181
  protocol:
    name: dubbo
    port: 20999
  consumer:
    timeout: 10000
